### ISSUE TITLE
pgp keeps failing following your instructions via Medium

### ISSUE THREAD

**Issue by kenaitian** [jaysavsani07/expense-manager#6]
Gpg keeps failing following your instructions via Medium and the comments section has more details to the issue:

Flutter CI/CD with Github Actions & Fastlane — Part 1(Android)

https://jaysavsani07.medium.com/flutter-ci-cd-with-github-actions-fastlane-part-1-android-14473438072d

I read somewhere that ~/.ssh/ed25519 is only allowed due to security for GitHub. 

Also, I wonder if importing GPG is more relevant than any gpg tools using Github Action per this article https://github.com/marketplace/actions/import-gpg. 

Please advise as error persists using another approach per this article - https://joshuamdeguzman.com/continuous-delivery-for-flutter-using-fastlane-and-github-actions-pt-2-android/:

0s
Run sh ./.github/scripts/decrypt_android_secrets.sh
gpg: directory '/home/runner/.gnupg' created
gpg: keybox '/home/runner/.gnupg/pubring.kbx' created
gpg: AES256 encrypted data
gpg: encrypted with 1 passphrase
gpg: decryption failed: Bad session key
Error: Process completed with exit code 2.

**Comment by jaysavsani07** [comment]
Happy to see that it helped you.
